version: "2.2"
services:
  backend:
    container_name: "backend"
    build: .
    image: myapp:latest
    volumes:
      - /home/project/Backend/project/public:/tmp
    ports:
      - "3000:80"
    restart: always
networks:
  default:
    external:
      name: project-network
